addSbtPlugin("com.eed3si9n"      % "sbt-projectmatrix" % "0.9.0")
addSbtPlugin("ch.epfl.scala"     % "sbt-bloop"         % "1032048a")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype"      % "3.9.15")
addSbtPlugin("com.github.sbt"    % "sbt-pgp"           % "2.1.2")
addSbtPlugin("de.heikoseeberger" % "sbt-header"        % "5.6.0")
