name: Publish Artifacts to OSS Sonatyep
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run unit tests
        run: sbt test
      - name: Run integration tests
        run: sbt it:test
      - name: Publish
        run: sbt "; + publishSigned; sonatypeBundleRelease"
