name: Publish Artifacts to OSS Sonatype
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run unit tests
        run: sbt test
      - name: Run integration tests
        run: sbt it:test
      - name: Publish artifacts
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          SONATYPE_LOGIN: ${{ secrets.SONATYPE_LOGIN }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        run: sbt "; + publishSigned; sonatypeBundleRelease"
